# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/model/hw7_2/hw7_2.cache/wt [current_project]
set_property parent.project_path E:/model/hw7_2/hw7_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib E:/model/hw7_2/hw7_2.srcs/sources_1/imports/new/Divisor.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/model/hw7_2/hw7_2.srcs/constrs_1/new/xdc.xdc
set_property used_in_implementation false [get_files E:/model/hw7_2/hw7_2.srcs/constrs_1/new/xdc.xdc]


synth_design -top Divider -part xc7a100tcsg324-1


write_checkpoint -force -noxdef Divider.dcp

catch { report_utilization -file Divider_utilization_synth.rpt -pb Divider_utilization_synth.pb }
