# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/model/bighw/bighw.cache/wt [current_project]
set_property parent.project_path E:/model/bighw/bighw.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  E:/model/bighw/bighw.srcs/sources_1/new/word1.v
  E:/model/bighw/bighw.srcs/sources_1/new/snake.v
  E:/model/bighw/bighw.srcs/sources_1/new/scoring.v
  E:/model/bighw/bighw.srcs/sources_1/new/word.v
  E:/model/bighw/bighw.srcs/sources_1/new/vga.v
  E:/model/bighw/bighw.srcs/sources_1/new/keyin.v
  E:/model/bighw/bighw.srcs/sources_1/new/clkdiv.v
  E:/model/bighw/bighw.srcs/sources_1/new/keyboard.v
  E:/model/bighw/bighw.srcs/sources_1/new/snake_top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/model/bighw/bighw.srcs/constrs_1/new/snake_xdc.xdc
set_property used_in_implementation false [get_files E:/model/bighw/bighw.srcs/constrs_1/new/snake_xdc.xdc]


synth_design -top snake_top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef snake_top.dcp

catch { report_utilization -file snake_top_utilization_synth.rpt -pb snake_top_utilization_synth.pb }
