# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/model/piano/piano.cache/wt [current_project]
set_property parent.project_path E:/model/piano/piano.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture.dcp
set_property used_in_implementation false [get_files C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture.dcp]
add_files -quiet C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock.dcp
set_property used_in_implementation false [get_files C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock.dcp]
add_files -quiet C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip.dcp
set_property used_in_implementation false [get_files C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip.dcp]
read_mem C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture.mif
read_verilog -library xil_defaultlib {
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/divider.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture_stub.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture_sim_netlist.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/sim/start_picture.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock_stub.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock_sim_netlist.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/vga.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/score_display.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/ps2_receiver.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/music_creator.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/music_choice.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/erase_controller.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/block_random.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/bin_dec.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip_stub.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip_sim_netlist.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip.v
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/new/top.v
}
read_vhdl -library xil_defaultlib {
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/synth/start_picture.vhd
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture_stub.vhdl
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/start_picture/start_picture_sim_netlist.vhdl
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock_stub.vhdl
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/block_drop_clock/block_drop_clock_sim_netlist.vhdl
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip_stub.vhdl
  C:/Users/86182/Desktop/Piano-Block-Game-main/Piano-Block-Game-main/ip/vga_ip/vga_ip_sim_netlist.vhdl
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
